### ISSUE TITLE
Update syntax_tree dependency to 6.0

### ISSUE THREAD

**Issue by olbrich** [nebulab/erb-formatter#16]
https://github.com/nebulab/erb-formatter/blob/6581ff405ee365c17f73c39869d2cf3705c5b3f5/erb-formatter.gemspec#L31

Syntax tree released a new version. Some other gems (like `ruby-lsp`) depend on this new version, which makes them conflict with this gem.

**Comment by elia** [comment]
Fixed in https://github.com/nebulab/erb-formatter/releases/tag/v0.4.3
