### ISSUE TITLE
Add sorting for TailwindCSS classes

### ISSUE THREAD

**Issue by elia** [nebulab/erb-formatter#26]
See https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted and https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/main/src/sorting.js.

**Comment by danieldocki** [comment]
would be wonderful

**Comment by elia** [comment]
Fixed by https://github.com/nebulab/erb-formatter/pull/39
