### ISSUE TITLE
Support globs for files to format

### ISSUE THREAD

**Issue by tmaier** [nebulab/erb-formatter#36]
I want to use a tool called "erb-format" to format all my `*.html.erb` and `*.turbo_stream.erb` files.

The issue is, it supports globs just poorly.
One would need to run the following to format all the files:

- `bin/erb-format **/*.{html,turbo_stream}.erb --write`
- `bin/erb-format **/**/*.{html,turbo_stream}.erb --write`
- `bin/erb-format **/**/**/*.{html,turbo_stream}.erb --write`
- `bin/erb-format **/**/**/**/*.{html,turbo_stream}.erb --write`
- ...

When any of them would not find a file, it raises an error like `No such file or directory @ rb_sysopen - app/**/*.turbo_stream.erb (Errno::ENOENT)`

I think `Dir.glob` could solve this...

```ruby
      files = 
        Dir.glob(@argv).map do |filename|
          [filename, File.read(filename)]
        end
```

**Comment by elia** [comment]
In theory the double asterisk should already recurse subdirectories, maybe it's not enabled in your shell env?

For bash you should be able to enable it with `shopt -s globstar`, see https://askubuntu.com/a/1010708.
