### ISSUE TITLE
Format unquotted attributes adding quotes to already quoted attributes

### ISSUE THREAD

**Issue by IbraheemTuffaha** [nebulab/erb-formatter#42]
The newest release of v0.7.1 by @x4d3 introduced format unquoted attributes.
In some cases, it's adding quotes to attributes that already have quotes, check the image below 👇 
<img width="1470" alt="image" src="https://github.com/nebulab/erb-formatter/assets/33587724/3a287d90-81ab-46c4-b9ea-8500cf77c3ee">
Seems to me like a weird edge case that needs to be handled.

**Comment by phil-janeapp** [comment]
To add some additional context, it appears to be happening on attributes that contain an `=` sign and are of at least a certain length (somewhere in the 50-60 character range?). I was able to have it happen on `<a href>` tags but only if the URL was of a certain length.

**Comment by mikker** [comment]
Happens for `<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">` as well.
