### ISSUE TITLE
Line length configurable?

### ISSUE THREAD

**Issue by sharkby7e** [nebulab/erb-formatter#49]
Couldn't find how to configure line length? Especially annoying with tailwind, want to just keep all class names on same line. Thanks!

**Comment by elia** [comment]
If you're using erb-formatter from the command line you can pass `-h` and get the full list of options:

```sh
$ erb-formatter -h
Usage: /Users/elia/.asdf/installs/ruby/3.3.0/bin/erb-formatter FILENAME... --write
    -w, --[no-]write                 Write file
        --stdin-filename FILEPATH    Set the stdin filename (implies --stdin)
        --[no-]stdin                 Read the file from stdin
        --print-width WIDTH          Set the formatted output width
        --single-class-per-line      Print each class on a separate line
        --tailwind-output-path PATH  Set the path to the tailwind output file
        --[no-]debug                 Enable debug mode
    -h, --help                       Prints this help
    -v, --version                    Show ERB::Formatter version number and quit
```

You can use the `--print-width` option to control line length, e.g. `erb-formatter --print-width 120 --write my-file.erb`.

Happy to reopen the issue if you need more info 👍

**Comment by sharkby7e** [comment]
i'm using erb-formatter as a part of [conform](https://github.com/stevearc/conform.nvim), and i'm wondering if i can pass the option in through my [configuration](https://github.com/sharkby7e/nvim/blob/main/lua/sharkby7e/plugins/conform.lua). I will try that option tho!
