### ISSUE TITLE
Ignore Front Matter

### ISSUE THREAD

**Issue by cseelus** [nebulab/erb-formatter#6]
Static site generators like [Bridgetown](https://middlemanapp.com) or [Middleman](https://middlemanapp.com), usually utilize some kinds of Front Matter, like

```
---
layout: post
title: Blogging Like a Hacker
---
```

Unfortunately `erb-format` will convert it to this, which doesn't work anymore:

```
--- layout: post title: Blogging Like a Hacker ---
```

Using a hash based syntax almost works …

```ruby
---<%
{
  layout: :post,
  title: 'Blogging Like a Hacker'
}
%>---
```

but will also get destroyed upon formating:

```ruby
---<% {
  layout: :post,
  title: 'Blogging Like a Hacker'
} %>
---
```

Is there any known workaround for this problem, like the `# rubocop:disable all` comment, which can be added to enclose lines that should be ignored? Would be happy to add this info to the README, if requested.

**Comment by elia** [comment]
@cseelus added https://github.com/nebulab/erb-formatter/pull/12, can you please try it out and check if there are any issues?

**Comment by cseelus** [comment]
It looks like all lines of the front matter get merged into one, so for example this test file …

```erb
---
layout: default
---

<h1 class="text-4xl mb-12"><%= resource.data.title %></h1>

  <div class="mx-auto lg:mx-48 xl:mx-72 2xl:mx-96">
    <%= yield %>
          </div>

```

… will be formatted correctly, except for the front matter:

<img width="506" alt="Screenshot 2023-01-17 at 14 17 57" src="https://user-images.githubusercontent.com/3188392/212908927-1faf41db-fdfa-4b27-a3f1-cd2af9f40f99.png">

**Comment by elia** [comment]
Maybe you tried with the installed version or one from master? Seems to be working here:

```
⤑ pbpaste | erb-format --stdin
---
layout: default
---

<h1 class="text-4xl mb-12"><%= resource.data.title %></h1>

<div class="mx-auto lg:mx-48 xl:mx-72 2xl:mx-96">
  <%= yield %>
</div>
```

**Comment by cseelus** [comment]
Weird, I cloned this repo (since I created a PR for a `--version` cmd line flag) and used this one.

Seems to not have picked up your commit/force push from ~10 minutes ago, will give it another try this afternoon:

<img width="318" alt="Screenshot 2023-01-17 at 14 32 26" src="https://user-images.githubusercontent.com/3188392/212912041-892e027e-e35f-4f22-961d-8589637c23f4.png">

<img width="1065" alt="Screenshot 2023-01-17 at 14 32 48" src="https://user-images.githubusercontent.com/3188392/212912121-076db782-4f0d-4869-b4a8-737cebc463b6.png">

**Comment by cseelus** [comment]
Your new changes from `elia/front-matter` seem to work great now, tested a bunch of files.

A improvement would be, to keep a blank line between the front matter and the actual eruby stuff, like in [this](https://www.bridgetownrb.com/docs/front-matter#custom-variables) or [that](https://middlemanapp.com/basics/frontmatter/) example.

Before:

```erb
---
layout: page
title: About
---

<p>This is the basic Bridgetown (BT) site template. You can find out more info about customizing your Bridgetown site, as well as basic Bridgetown usage documentation at [bridgetownrb.com](https://bridgetownrb.com/)</p>
```

After:

```shell
$ erb-format src/about.erb --no-write
```

```erb
---
layout: page
title: About
---
<p>This is the basic Bridgetown (BT) site template. You can find out more info
  about customizing your Bridgetown site, as well as basic Bridgetown usage
  documentation at [bridgetownrb.com](https://bridgetownrb.com/)</p>
```

One other thing, since I couldn't find anything in the docs: The max line length can only be set indirectly via `RuboCop::Cop::Layout::LineLength#max`?

**Comment by elia** [comment]
> One other thing, since I couldn't find anything in the docs: The max line length can only be set indirectly via `RuboCop::Cop::Layout::LineLength#max`?

Does #13 solve?

**Comment by elia** [comment]
Pushed an update that will add an extra newline, good call 👍

**Comment by cseelus** [comment]
Newline-update works as expected 👌

Would be cool if one could disable forced line breaks altogether via #13.

I'm on the road now with a smaller screen and those newlines can mess things up:

Before running `erb-format`:
<img width="637" alt="Screenshot 2023-01-17 at 16 36 24" src="https://user-images.githubusercontent.com/3188392/212941779-822f889f-eca8-418c-9ea9-76fc6fa43cb2.png">

After:
<img width="609" alt="Screenshot 2023-01-17 at 16 36 40" src="https://user-images.githubusercontent.com/3188392/212941854-0d04a257-885c-46c2-ae57-07c97ad30d97.png">
